### ISSUE TITLE
VehicleDestroyEvent getAttacker returning null

### ISSUE THREAD

**Issue by Megachin502** [Jessy1237/DwarfCraft#20]
[13:40:41] [Server thread/ERROR]: Could not pass event VehicleDestroyEvent to DwarfCraft v3.1.2
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
at net.minecraft.server.v1_10_R1.EntityMinecartAbstract.damageEntity(EntityMinecartAbstract.java:148) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
at net.minecraft.server.v1_10_R1.Entity.burn(Entity.java:916) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
at net.minecraft.server.v1_10_R1.Entity.move(Entity.java:781) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
at net.minecraft.server.v1_10_R1.EntityMinecartAbstract.q(EntityMinecartAbstract.java:410) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
at net.minecraft.server.v1_10_R1.EntityMinecartAbstract.m(EntityMinecartAbstract.java:302) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
at net.minecraft.server.v1_10_R1.World.entityJoinedWorld(World.java:1629) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
at net.minecraft.server.v1_10_R1.World.g(World.java:1604) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
at net.minecraft.server.v1_10_R1.World.tickEntities(World.java:1430) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
at net.minecraft.server.v1_10_R1.WorldServer.tickEntities(WorldServer.java:632) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:799) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.NullPointerException
at com.Jessy1237.DwarfCraft.listeners.DCVehicleListener.onVehicleDestroy(DCVehicleListener.java:45) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_101]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
... 17 more

**Comment by Megachin502** [comment]
Same specs as the last issue. Not sure when this happens but someone logged in right after not sure.

**Comment by Megachin502** [comment]
Could not pass event VehicleDestroyEvent to DwarfCraft v3.1.2

org.bukkit.event.EventException

	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]

	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]

	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]

	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]

	at net.minecraft.server.v1_10_R1.EntityMinecartAbstract.damageEntity(EntityMinecartAbstract.java:148) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]

	at net.minecraft.server.v1_10_R1.Entity.burn(Entity.java:916) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]

	at net.minecraft.server.v1_10_R1.Entity.move(Entity.java:781) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]

	at net.minecraft.server.v1_10_R1.EntityMinecartAbstract.q(EntityMinecartAbstract.java:410) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]

	at net.minecraft.server.v1_10_R1.EntityMinecartAbstract.m(EntityMinecartAbstract.java:302) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]

	at net.minecraft.server.v1_10_R1.World.entityJoinedWorld(World.java:1629) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]

	at net.minecraft.server.v1_10_R1.World.g(World.java:1604) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]

	at net.minecraft.server.v1_10_R1.World.tickEntities(World.java:1430) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]

	at net.minecraft.server.v1_10_R1.WorldServer.tickEntities(WorldServer.java:632) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]

	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:799) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]

	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]

	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]

	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]

	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]

Caused by: java.lang.NullPointerException

	at com.Jessy1237.DwarfCraft.listeners.DCVehicleListener.onVehicleDestroy(DCVehicleListener.java:45) ~[?:?]

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_101]

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]

	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]

	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]

	... 17 more

[13:41:11] [User Authenticator #5\/INFO]: UUID of player immorticide is 2be12c89-677a-435b-86de-d2da573c086b

**Comment by drekryan** [comment]
@Jessy1237, not at my computer to test it at the moment but I believe it probably has to do with something being null when you are creating the DCEffect Event around line 65 of onVehicleDestroy in the Vehicle Listener. I would say it's the event.getVehicle().getVehicle(). But I would have to open my code editor to double check which I can do later unless you fix the issue before.

**Comment by Megachin502** [comment]
I havent been able to reproduce it

**Comment by Jessy1237** [comment]
I think somehow a boat broke but not by an entity, so the attacker variable was null
