### ISSUE TITLE
Dwarfcraft 4.0 not work in spigot 1.12

### ISSUE THREAD

**Issue by SnUncle** [Jessy1237/DwarfCraft#39]
Check this 
there is my plugins : 
LuckPerms
Vault
Citizens2
Dwarfcraft

[17:50:06] [Server thread/INFO]: Starting minecraft server version 1.12
[17:50:06] [Server thread/INFO]: Loading properties
[17:50:06] [Server thread/INFO]: Default game type: SURVIVAL
[17:50:06] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-596221b-9a1fc1e (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)
[17:50:06] [Server thread/INFO]: Debug logging is disabled
[17:50:06] [Server thread/INFO]: Using 4 threads for Netty based IO
[17:50:06] [Server thread/INFO]: Server Ping Player Sample Count: 12
[17:50:06] [Server thread/INFO]: Generating keypair
[17:50:06] [Server thread/INFO]: Starting Minecraft server on 127.0.0.1:25565
[17:50:06] [Server thread/INFO]: Using default channel type
[17:50:06] [Server thread/INFO]: Set PluginClassLoader as parallel capable
[17:50:06] [Server thread/INFO]: [LuckPerms] Loading LuckPerms v4.0.80
[17:50:06] [Server thread/INFO]: [0;37;22m[21m[[0;36;1mL[0;36;22mP[0;37;22m[21m] [0;36;22mIdentified the following dependencies: [CAFFEINE][m
[17:50:06] [Server thread/INFO]: [Vault] Loading Vault v1.5.6-b49
[17:50:06] [Server thread/INFO]: [Citizens] Loading Citizens v2.0.22-SNAPSHOT (build 1496)
[17:50:06] [Server thread/INFO]: [DwarfCraft] Loading DwarfCraft v4.0
[17:50:06] [Server thread/INFO]: [LuckPerms] Enabling LuckPerms v4.0.80
[17:50:06] [Server thread/INFO]: [0;36;1m               __       [0;36;22m __   ___  __         __  [m
[17:50:06] [Server thread/INFO]: [0;36;1m    |    |  | /  ` |__/ [0;36;22m|__) |__  |__)  |\/| /__` [m
[17:50:06] [Server thread/INFO]: [0;36;1m    |___ \__/ \__, |  \ [0;36;22m|    |___ |  \  |  | .__/ [m
[17:50:06] [Server thread/INFO]:  [m
[17:50:06] [Server thread/INFO]: [0;32;22m  Loading version [0;36;1mv4.0.80[0;32;22m on Bukkit - CraftBukkit[m
[17:50:06] [Server thread/INFO]: [0;30;1m  Running on server version git-Spigot-596221b-9a1fc1e (MC: 1.12) - 1.12-R0.1-SNAPSHOT[m
[17:50:06] [Server thread/INFO]:  [m
[17:50:06] [Server thread/INFO]: [0;37;22m[21m[[0;36;1mL[0;36;22mP[0;37;22m[21m] [0;36;22mLoading configuration...[m
[17:50:06] [Server thread/INFO]: [0;37;22m[21m[[0;36;1mL[0;36;22mP[0;37;22m[21m] [0;36;22mIdentified the following dependencies: [H2_DRIVER][m
[17:50:06] [Server thread/INFO]: [0;37;22m[21m[[0;36;1mL[0;36;22mP[0;37;22m[21m] [0;36;22mLoading storage provider... [H2][m
[17:50:07] [Server thread/INFO]: [0;37;22m[21m[[0;36;1mL[0;36;22mP[0;37;22m[21m] [0;36;22mFound lang.yml - loading messages...[m
[17:50:07] [Server thread/INFO]: [0;37;22m[21m[[0;36;1mL[0;36;22mP[0;37;22m[21m] [0;36;22mLoading internal permission managers...[m
[17:50:07] [Server thread/INFO]: [0;37;22m[21m[[0;36;1mL[0;36;22mP[0;37;22m[21m] [0;36;22mPerforming initial data load...[m
[17:50:07] [Server thread/INFO]: [0;37;22m[21m[[0;36;1mL[0;36;22mP[0;37;22m[21m] [0;36;22mSuccessfully enabled. (took 818ms)[m
[17:50:07] [Server thread/INFO]: [Vault] Enabling Vault v1.5.6-b49
[17:50:07] [Server thread/INFO]: [Vault] [Permission] SuperPermissions loaded as backup permission system.
[17:50:07] [Server thread/INFO]: [Vault] Enabled Version 1.5.6-b49
[17:50:07] [Server thread/INFO]: [0;37;22m[21m[[0;36;1mL[0;36;22mP[0;37;22m[21m] [0;36;22mRegistered Vault permission & chat hook.[m
[17:50:07] [Server thread/WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[17:50:07] [Server thread/WARN]: The server will make no attempt to authenticate usernames. Beware.
[17:50:07] [Server thread/WARN]: While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
[17:50:07] [Server thread/WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[17:50:07] [Server thread/INFO]: **** Beginning UUID conversion, this may take A LONG time ****
[17:50:07] [Server thread/INFO]: Preparing level "world"
[17:50:07] [Server thread/INFO]: -------- World Settings For [world] --------
[17:50:07] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[17:50:07] [Server thread/INFO]: View Distance: 10
[17:50:07] [Server thread/INFO]: Arrow Despawn Rate: 1200
[17:50:07] [Server thread/INFO]: Item Merge Radius: 2.5
[17:50:07] [Server thread/INFO]: Item Despawn Rate: 6000
[17:50:07] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[17:50:07] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[17:50:07] [Server thread/INFO]: Experience Merge Radius: 3.0
[17:50:07] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[17:50:07] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[17:50:07] [Server thread/INFO]: Random Lighting Updates: false
[17:50:07] [Server thread/INFO]: Structure Info Saving: true
[17:50:07] [Server thread/INFO]: Mob Spawn Range: 4
[17:50:07] [Server thread/INFO]: Max TNT Explosions: 100
[17:50:07] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[17:50:07] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617 Monument: 10387313 Slime: 987234911
[17:50:07] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[17:50:07] [Server thread/INFO]: Cactus Growth Modifier: 100%
[17:50:07] [Server thread/INFO]: Cane Growth Modifier: 100%
[17:50:07] [Server thread/INFO]: Melon Growth Modifier: 100%
[17:50:07] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[17:50:07] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[17:50:07] [Server thread/INFO]: Sapling Growth Modifier: 100%
[17:50:07] [Server thread/INFO]: Wheat Growth Modifier: 100%
[17:50:07] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[17:50:07] [Server thread/INFO]: Vine Growth Modifier: 100%
[17:50:07] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[17:50:08] [Server thread/INFO]: -------- World Settings For [world_nether] --------
[17:50:08] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[17:50:08] [Server thread/INFO]: View Distance: 10
[17:50:08] [Server thread/INFO]: Arrow Despawn Rate: 1200
[17:50:08] [Server thread/INFO]: Item Merge Radius: 2.5
[17:50:08] [Server thread/INFO]: Item Despawn Rate: 6000
[17:50:08] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[17:50:08] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[17:50:08] [Server thread/INFO]: Experience Merge Radius: 3.0
[17:50:08] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[17:50:08] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[17:50:08] [Server thread/INFO]: Random Lighting Updates: false
[17:50:08] [Server thread/INFO]: Structure Info Saving: true
[17:50:08] [Server thread/INFO]: Mob Spawn Range: 4
[17:50:08] [Server thread/INFO]: Max TNT Explosions: 100
[17:50:08] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[17:50:08] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617 Monument: 10387313 Slime: 987234911
[17:50:08] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[17:50:08] [Server thread/INFO]: Cactus Growth Modifier: 100%
[17:50:08] [Server thread/INFO]: Cane Growth Modifier: 100%
[17:50:08] [Server thread/INFO]: Melon Growth Modifier: 100%
[17:50:08] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[17:50:08] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[17:50:08] [Server thread/INFO]: Sapling Growth Modifier: 100%
[17:50:08] [Server thread/INFO]: Wheat Growth Modifier: 100%
[17:50:08] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[17:50:08] [Server thread/INFO]: Vine Growth Modifier: 100%
[17:50:08] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[17:50:08] [Server thread/INFO]: -------- World Settings For [world_the_end] --------
[17:50:08] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[17:50:08] [Server thread/INFO]: View Distance: 10
[17:50:08] [Server thread/INFO]: Arrow Despawn Rate: 1200
[17:50:08] [Server thread/INFO]: Item Merge Radius: 2.5
[17:50:08] [Server thread/INFO]: Item Despawn Rate: 6000
[17:50:08] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[17:50:08] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[17:50:08] [Server thread/INFO]: Experience Merge Radius: 3.0
[17:50:08] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[17:50:08] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[17:50:08] [Server thread/INFO]: Random Lighting Updates: false
[17:50:08] [Server thread/INFO]: Structure Info Saving: true
[17:50:08] [Server thread/INFO]: Mob Spawn Range: 4
[17:50:08] [Server thread/INFO]: Max TNT Explosions: 100
[17:50:08] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[17:50:08] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617 Monument: 10387313 Slime: 987234911
[17:50:08] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[17:50:08] [Server thread/INFO]: Cactus Growth Modifier: 100%
[17:50:08] [Server thread/INFO]: Cane Growth Modifier: 100%
[17:50:08] [Server thread/INFO]: Melon Growth Modifier: 100%
[17:50:08] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[17:50:08] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[17:50:08] [Server thread/INFO]: Sapling Growth Modifier: 100%
[17:50:08] [Server thread/INFO]: Wheat Growth Modifier: 100%
[17:50:08] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[17:50:08] [Server thread/INFO]: Vine Growth Modifier: 100%
[17:50:08] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[17:50:08] [Server thread/INFO]: Preparing start region for level 0 (Seed: -3194798693216740247)
[17:50:09] [Server thread/INFO]: Preparing spawn area: 64%
[17:50:09] [Server thread/INFO]: Preparing start region for level 1 (Seed: -7837347383460679215)
[17:50:10] [Server thread/INFO]: Preparing start region for level 2 (Seed: -7837347383460679215)
[17:50:10] [Server thread/INFO]: [Citizens] Enabling Citizens v2.0.22-SNAPSHOT (build 1496)
[17:50:10] [Server thread/ERROR]: [Citizens] Missing preferred location bundle.
[17:50:10] [Server thread/INFO]: [DwarfCraft] Enabling DwarfCraft v4.0
[17:50:10] [Server thread/INFO]: [DwarfCraft] Hooked into Citizens!
[17:50:10] [Server thread/INFO]: [DwarfCraft] Reading Config File: D:\minecraftabout\1.12CAF\plugins\DwarfCraft\DwarfCraft.config
[17:50:10] [Server thread/INFO]: [DwarfCraft] Loaded vanilla race: Vanilla
[17:50:10] [Server thread/INFO]: [DwarfCraft] Reading Config File: D:\minecraftabout\1.12CAF\plugins\DwarfCraft\DwarfCraft.config
[17:50:10] [Server thread/INFO]: [DwarfCraft] Reading skills file: D:\minecraftabout\1.12CAF\plugins\DwarfCraft\skills.csv
[17:50:10] [Server thread/INFO]: [DwarfCraft] Reading effects file: D:\minecraftabout\1.12CAF\plugins\DwarfCraft\effects.csv
[17:50:10] [Server thread/INFO]: DC ERROR: Could not parse material: 29LEATHER_CHESTPLATE9
[17:50:10] [Server thread/INFO]: [DwarfCraft] Reading messages file: D:\minecraftabout\1.12CAF\plugins\DwarfCraft\messages.config
[17:50:10] [Server thread/INFO]: [DwarfCraft] Reading world blacklist file: D:\minecraftabout\1.12CAF\plugins\DwarfCraft\world-blacklist.config
[17:50:10] [Server thread/INFO]: [DwarfCraft] Reading races file: D:\minecraftabout\1.12CAF\plugins\DwarfCraft\races.config
[17:50:10] [Server thread/INFO]: [DwarfCraft] Loaded race: Dwarf
[17:50:10] [Server thread/INFO]: [DwarfCraft] Loaded race: Elf
[17:50:10] [Server thread/INFO]: [DwarfCraft] Loaded race: Gnome
[17:50:10] [Server thread/INFO]: [DwarfCraft] Loaded race: Human
[17:50:10] [Server thread/INFO]: [DwarfCraft] Reading Block Groups file: D:\minecraftabout\1.12CAF\plugins\DwarfCraft\block-groups.config
[17:50:10] [Server thread/INFO]: [DwarfCraft] Reading Tool Groups file: D:\minecraftabout\1.12CAF\plugins\DwarfCraft\tool-groups.config
[17:50:10] [Server thread/INFO]: [DwarfCraft] Reading Aliases file: D:\minecraftabout\1.12CAF\plugins\DwarfCraft\aliases.config
[17:50:10] [Server thread/INFO]: [DwarfCraft] Reading greeter messages file: D:\minecraftabout\1.12CAF\plugins\DwarfCraft\greeters.config
[17:50:10] [Server thread/ERROR]: Error occurred while enabling DwarfCraft v4.0 (Is it up to date?)
java.lang.NullPointerException: null
	at com.Jessy1237.DwarfCraft.Util.removePlayerPrefixes(Util.java:459) ~[?:?]
	at com.Jessy1237.DwarfCraft.DwarfCraft.onEnable(DwarfCraft.java:459) ~[?:?]
	at com.Jessy1237.DwarfCraft.DwarfCraft.onEnable(DwarfCraft.java:375) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:374) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:323) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
[17:50:10] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[17:50:11] [Server thread/INFO]: Done (3.349s)! For help, type "help" or "?"
[17:50:11] [Server thread/ERROR]: [Citizens] The trait npcdestinations failed to load for NPC ID: 13.
[17:50:11] [Server thread/INFO]: [Citizens] NPC type EntityHorse was not recognized. Did you spell it correctly?
[17:50:11] [Server thread/ERROR]: [Citizens] The trait sentry failed to load for NPC ID: 279.
[17:50:11] [Server thread/ERROR]: [Citizens] The trait trader failed to load for NPC ID: 339.
[17:50:11] [Server thread/ERROR]: [Citizens] The trait wallet failed to load for NPC ID: 339.
[17:50:11] [Server thread/ERROR]: [Citizens] The trait trader failed to load for NPC ID: 346.
[17:50:11] [Server thread/ERROR]: [Citizens] The trait wallet failed to load for NPC ID: 346.
[17:50:11] [Server thread/ERROR]: [Citizens] The trait sentinel failed to load for NPC ID: 351.
[17:50:11] [Server thread/ERROR]: [Citizens] The trait wallet failed to load for NPC ID: 388.
[17:50:11] [Server thread/ERROR]: [Citizens] The trait trader failed to load for NPC ID: 388.
[17:50:11] [Server thread/ERROR]: [Citizens] The trait wallet failed to load for NPC ID: 403.
[17:50:11] [Server thread/ERROR]: [Citizens] The trait trader failed to load for NPC ID: 403.
[17:50:11] [Server thread/ERROR]: [Citizens] The trait sentry failed to load for NPC ID: 469.
[17:50:11] [Server thread/ERROR]: [Citizens] The trait assignment failed to load for NPC ID: 469.
[17:50:11] [Server thread/ERROR]: [Citizens] The trait sentinel failed to load for NPC ID: 469.
[17:50:11] [Server thread/ERROR]: [Citizens] The trait triggers failed to load for NPC ID: 469.
[17:50:11] [Server thread/ERROR]: [Citizens] The trait npcdestinations failed to load for NPC ID: 469.
[17:50:11] [Server thread/ERROR]: [Citizens] The trait sentry failed to load for NPC ID: 474.
[17:50:11] [Server thread/ERROR]: [Citizens] The trait fishing failed to load for NPC ID: 554.
[17:50:11] [Server thread/ERROR]: [Citizens] The trait assignment failed to load for NPC ID: 554.
[17:50:11] [Server thread/ERROR]: [Citizens] The trait triggers failed to load for NPC ID: 554.
[17:50:11] [Server thread/ERROR]: [Citizens] The trait npcdestinations failed to load for NPC ID: 551.
[17:50:11] [Server thread/ERROR]: [Citizens] The trait assignment failed to load for NPC ID: 555.
[17:50:11] [Server thread/ERROR]: [Citizens] The trait triggers failed to load for NPC ID: 555.
[17:50:11] [Server thread/ERROR]: [Citizens] The trait shopkeeper failed to load for NPC ID: 561.
[17:50:11] [Server thread/ERROR]: [Citizens] The trait trader failed to load for NPC ID: 562.
[17:50:11] [Server thread/ERROR]: [Citizens] The trait npcdestinations failed to load for NPC ID: 562.
[17:50:11] [Server thread/ERROR]: [Citizens] The trait wallet failed to load for NPC ID: 562.
[17:50:11] [Server thread/ERROR]: [Citizens] The trait assignment failed to load for NPC ID: 564.
[17:50:11] [Server thread/ERROR]: [Citizens] The trait triggers failed to load for NPC ID: 564.
[17:50:11] [Server thread/ERROR]: [Citizens] The trait trader failed to load for NPC ID: 568.
[17:50:11] [Server thread/ERROR]: [Citizens] The trait wallet failed to load for NPC ID: 568.
[17:50:11] [Server thread/ERROR]: [Citizens] The trait npcdestinations failed to load for NPC ID: 581.
[17:50:11] [Server thread/ERROR]: [Citizens] The trait trader failed to load for NPC ID: 581.
[17:50:11] [Server thread/ERROR]: [Citizens] The trait wallet failed to load for NPC ID: 581.
[17:50:11] [Server thread/ERROR]: [Citizens] The trait sentinel failed to load for NPC ID: 584.
[17:50:11] [Server thread/ERROR]: [Citizens] The trait sentinel failed to load for NPC ID: 582.
[17:50:11] [Server thread/ERROR]: [Citizens] The trait trader failed to load for NPC ID: 596.
[17:50:11] [Server thread/ERROR]: [Citizens] The trait wallet failed to load for NPC ID: 596.
[17:50:11] [Server thread/ERROR]: [Citizens] The trait npcdestinations failed to load for NPC ID: 606.
[17:50:11] [Server thread/ERROR]: [Citizens] The trait assignment failed to load for NPC ID: 606.
[17:50:11] [Server thread/ERROR]: [Citizens] The trait triggers failed to load for NPC ID: 606.
[17:50:11] [Server thread/ERROR]: [Citizens] The trait sentinel failed to load for NPC ID: 606.
[17:50:11] [Server thread/ERROR]: [Citizens] The trait assignment failed to load for NPC ID: 607.
[17:50:11] [Server thread/ERROR]: [Citizens] The trait sentinel failed to load for NPC ID: 607.
[17:50:11] [Server thread/ERROR]: [Citizens] The trait npcdestinations failed to load for NPC ID: 607.
[17:50:11] [Server thread/ERROR]: [Citizens] The trait triggers failed to load for NPC ID: 607.
[17:50:11] [Server thread/ERROR]: [Citizens] The trait trader failed to load for NPC ID: 608.
[17:50:11] [Server thread/ERROR]: [Citizens] The trait wallet failed to load for NPC ID: 608.
[17:50:11] [Server thread/ERROR]: [Citizens] The trait npcdestinations failed to load for NPC ID: 608.
[17:50:11] [Server thread/ERROR]: [Citizens] The trait sentinel failed to load for NPC ID: 608.
[17:50:11] [Server thread/ERROR]: [Citizens] The trait wallet failed to load for NPC ID: 612.
[17:50:11] [Server thread/ERROR]: [Citizens] The trait trader failed to load for NPC ID: 612.
[17:50:11] [Server thread/ERROR]: [Citizens] The trait npcdestinations failed to load for NPC ID: 624.
[17:50:11] [Server thread/ERROR]: [Citizens] The trait sentinel failed to load for NPC ID: 627.
[17:50:11] [Server thread/ERROR]: [Citizens] The trait npcdestinations failed to load for NPC ID: 625.
[17:50:11] [Server thread/ERROR]: [Citizens] The trait sentinel failed to load for NPC ID: 642.
[17:50:11] [Server thread/INFO]: [Citizens] Loaded 129 NPCs.
[17:50:11] [Craft Scheduler Thread - 5/INFO]: [Vault] Checking for Updates ... 
[17:50:12] [Server thread/INFO]: Unknown command. Type "/help" for help.[m
[17:50:13] [Server thread/INFO]: Scanning for legacy world dragon fight...
[17:50:13] [Server thread/INFO]: Found that the dragon has not yet been killed in this world.
[17:50:15] [Craft Scheduler Thread - 5/INFO]: [Vault] No new version available
[17:50:26] [User Authenticator #1/INFO]: UUID of player SnUncle is 204535d4-7b38-3753-bb8e-d739eeb76617
[17:50:26] [Server thread/INFO]: SnUncle[/127.0.0.1:50717] logged in with entity id 414 at ([world]-132.64155174717064, 67.0, 700.28846884712)
[17:50:30] [Server thread/INFO]: SnUncle issued server command: /dc
[17:50:32] [Server thread/INFO]: SnUncle issued server command: /dc reload
[17:50:32] [Server thread/INFO]: [DwarfCraft] Reloading...
[17:50:32] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'dc' in plugin DwarfCraft v4.0
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1385) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1220) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_144]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_144]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
Caused by: java.lang.NullPointerException
	at com.Jessy1237.DwarfCraft.Util.removePlayerPrefixes(Util.java:459) ~[?:?]
	at com.Jessy1237.DwarfCraft.DwarfCraft.onDisable(DwarfCraft.java:366) ~[?:?]
	at com.Jessy1237.DwarfCraft.commands.CommandReload.execute(CommandReload.java:39) ~[?:?]
	at com.Jessy1237.DwarfCraft.DwarfCraft.onCommand(DwarfCraft.java:355) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	... 15 more

**Comment by drekryan** [comment]
What permissions plugin do you use? latest vault and citizens version? can you zip your Dwarfcraft config folder and upload to dropbox or something and link it here?

**Comment by Jessy1237** [comment]
I've used PermissionsEX and I do not get this issue, however when i used LuckPerms i do seem to get this issue. So i'll do some investigating with LuckPerms and see if i can resolve this issue.

**Comment by SnUncle** [comment]
yeah i think its a problem with LuckPerms 
thx for yall

**Comment by Jessy1237** [comment]
The fix has been uploaded to spigot
